<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('products')->insert([
            [
                'photo' => 'photos/asus_rog_zephyrus_g14.jpg',
                'product_name' => 'Asus ROG Zephyrus G14',
                'description' => 'Gaming laptop with AMD Ryzen 9 and NVIDIA RTX 3060.',
                'brand' => 'Asus',
                'cpu' => 'AMD Ryzen 9 5900HS',
                'gpu' => 'NVIDIA GeForce RTX 3060',
                'memory' => '16GB DDR4',
                'storage' => '1TB SSD',
                'stock' => 20,
                'price' => 25000000,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/dell_xps_13.jpg',
                'product_name' => 'Dell XPS 13',
                'description' => 'Ultrabook with Intel Core i7 and integrated graphics.',
                'brand' => 'Dell',
                'cpu' => 'Intel Core i7-1165G7',
                'gpu' => 'Intel Iris Xe',
                'memory' => '16GB LPDDR4x',
                'storage' => '512GB SSD',
                'stock' => 15,
                'price' => 20000000,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/hp_pavilion_gaming_15.jpeg',
                'product_name' => 'HP Pavilion Gaming 15',
                'description' => 'Affordable gaming laptop with AMD Ryzen 5 and NVIDIA GTX 1650.',
                'brand' => 'HP',
                'cpu' => 'AMD Ryzen 5 4600H',
                'gpu' => 'NVIDIA GeForce GTX 1650',
                'memory' => '8GB DDR4',
                'storage' => '512GB SSD',
                'stock' => 25,
                'price' => 15000000,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/lenovo_legion_5_pro.png',
                'product_name' => 'Lenovo Legion 5 Pro',
                'description' => 'High-performance gaming laptop with Ryzen 7 and RTX 3070.',
                'brand' => 'Lenovo',
                'cpu' => 'AMD Ryzen 7 5800H',
                'gpu' => 'NVIDIA GeForce RTX 3070',
                'memory' => '16GB DDR4',
                'storage' => '1TB SSD',
                'stock' => 10,
                'price' => 28000000,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/apple_macbook_pro_14.jpeg',
                'product_name' => 'Apple MacBook Pro 14',
                'description' => 'Laptop with M1 Pro chip, great for professionals.',
                'brand' => 'Apple',
                'cpu' => 'Apple M1 Pro',
                'gpu' => 'Integrated 16-core GPU',
                'memory' => '16GB Unified',
                'storage' => '512GB SSD',
                'stock' => 12,
                'price' => 30000000,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/msi_stealth_15m.jpg',
                'product_name' => 'MSI Stealth 15M',
                'description' => 'Thin and light gaming laptop with Intel Core i7.',
                'brand' => 'MSI',
                'cpu' => 'Intel Core i7-11800H',
                'gpu' => 'NVIDIA GeForce RTX 3060',
                'memory' => '16GB DDR4',
                'storage' => '512GB SSD',
                'stock' => 18,
                'price' => 22000000,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/razer_blade_15.jpg',
                'product_name' => 'Razer Blade 15',
                'description' => 'Premium gaming laptop with RTX 3070 and Intel Core i7.',
                'brand' => 'Razer',
                'cpu' => 'Intel Core i7-10875H',
                'gpu' => 'NVIDIA GeForce RTX 3070',
                'memory' => '16GB DDR4',
                'storage' => '1TB SSD',
                'stock' => 8,
                'price' => 35000000,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/acer_nitro_5.jpg',
                'product_name' => 'Acer Nitro 5',
                'description' => 'Affordable gaming laptop with powerful specs.',
                'brand' => 'Acer',
                'cpu' => 'AMD Ryzen 5 5600H',
                'gpu' => 'NVIDIA GeForce GTX 1650',
                'memory' => '8GB DDR4',
                'storage' => '256GB SSD',
                'stock' => 30,
                'price' => 14000000,
                'category_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/gigabyte_aorus_15g.jpeg',
                'product_name' => 'Gigabyte Aorus 15G',
                'description' => 'Gaming laptop with RTX 3080 and mechanical keyboard.',
                'brand' => 'Gigabyte',
                'cpu' => 'Intel Core i7-11800H',
                'gpu' => 'NVIDIA GeForce RTX 3080',
                'memory' => '32GB DDR4',
                'storage' => '1TB SSD',
                'stock' => 5,
                'price' => 40000000,
                'category_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'photo' => 'photos/samsung_galaxy_book_pro.jpeg',
                'product_name' => 'Samsung Galaxy Book Pro',
                'description' => 'Ultra-light laptop with AMOLED display.',
                'brand' => 'Samsung',
                'cpu' => 'Intel Core i5-1135G7',
                'gpu' => 'Intel Iris Xe',
                'memory' => '8GB LPDDR4x',
                'storage' => '512GB SSD',
                'stock' => 20,
                'price' => 18000000,
                'category_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
